WebHocAnhVanNew/Controllers/KhoaHocController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebHocAnhVanNew.Models;


namespace WebHocAnhVan.Controllers
{
    public class KhoaHocController : Controller
    {
        // GET: KhoaHoc
        MyDataDataContext data = new MyDataDataContext();
        public ActionResult ListKH(string searchBy, string search)
        {
            if (searchBy == "TenKhoaHoc")
                return View(data.KhoaHocs.Where(s => s.TenKhoaHoc.StartsWith(search)).ToList());
            else if (searchBy == "GiangVien")
                return View(data.Giangviens.Where(s => s.Id.StartsWith(search)).ToList());
            else
                return View(data.KhoaHocs.ToList());
        }
        public ActionResult CreateKH()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateKH(FormCollection collection, KhoaHoc KH)
        {
            var E_IdKH = collection["idkh"];
            var E_TenKH = collection["tenkh"];
            var E_MoTa = collection["mota"];
            var E_Gia = collection["gia"];
            var E_NgayXB = collection["ngayXB"];
            var E_Hinh = collection["hinh"];
            var E_IdGV = collection["IdGV"];


            if (string.IsNullOrEmpty(E_TenKH))
            {
                ViewData["Error"] = "Don't empty!";
            }
            else
            {
                KH.IdKhoaHoc = int.Parse(E_IdKH);
                KH.TenKhoaHoc = E_TenKH.ToString();
                KH.Mota = E_MoTa.ToString();
                KH.Gia = (decimal?)double.Parse(E_Gia);
                KH.NgayXuatBan = E_NgayXB.ToString();
                KH.Hinh = E_Hinh.ToString();
                KH.IdGV = int.Parse(E_IdGV);
                data.KhoaHocs.InsertOnSubmit(KH);
                data.SubmitChanges();
                return RedirectToAction("ListKH");
            }
            return this.CreateKH();
        }
        [Authorize]
        public ActionResult Buy(int id)
        {
            MyDataDataContext context = new MyDataDataContext();
            KhoaHoc khoaHoc = context.KhoaHocs.SingleOrDefault(p => p.IdKhoaHoc == id);
            if (khoaHoc == null)
            {
                return HttpNotFound();

            }
            return View(khoaHoc);
        }
        public ActionResult EditKH(int id)
        {
            var E_Khoahoc = data.KhoaHocs.First(m => m.IdKhoaHoc == id);
            return View(E_Khoahoc);
        }
        [HttpPost]
        public ActionResult EditKH(int id, FormCollection collection)
        {
            var E_KhoaHoc = data.KhoaHocs.First(m => m.IdKhoaHoc == id);
            var E_TenKH = collection["tenkh"];
            var E_MoTa = collection["mota"];
            var E_Gia = collection["gia"];
            var E_NgayXB = collection["ngayXB"];
            var E_Hinh = collection["hinh"];
            var E_IdGV = collection["IdGV"];
            E_KhoaHoc.IdKhoaHoc = id;
            if (string.IsNullOrEmpty(E_TenKH))
            {
                ViewData["Error"] = "Don't empty!";
            }
            else
            {   
                E_KhoaHoc.TenKhoaHoc = E_TenKH;
                E_KhoaHoc.Mota = E_MoTa;
                E_KhoaHoc.Gia = (decimal?)double.Parse(E_Gia);
                E_KhoaHoc.NgayXuatBan = E_NgayXB;
                E_KhoaHoc.Hinh = E_Hinh;
                E_KhoaHoc.IdGV = int.Parse(E_IdGV);
                UpdateModel(E_KhoaHoc);
                data.SubmitChanges();
                return RedirectToAction("ListKH");
            }
            return this.EditKH(id);
        }
        public ActionResult Delete(int id)
        {
            var D_KhoaHoc = data.KhoaHocs.First(m => m.IdKhoaHoc == id);
            return View(D_KhoaHoc);
        }
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            var D_KhoaHoc = data.KhoaHocs.Where(m => m.IdKhoaHoc == id).First();
            data.KhoaHocs.DeleteOnSubmit(D_KhoaHoc);
            data.SubmitChanges();
            return RedirectToAction("ListKH");
        }

    }
}

WebHocAnhVanNew/Views/KhoaHoc/Buy.cshtml
@model WebHocAnhVanNew.Models.KhoaHoc
@{
    ViewBag.Title = "Buy";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Buy</h2>


<br />
<p style="font-size:24px">Bạn đã mua <strong>@Model.TenKhoaHoc</strong>với giá<strong>@Model.Gia</strong>VND</p><strong><img src="@Model.Hinh" width="260px"height="300px" /></strong></p>
@Html.ActionLink("Noi Dung", "KhoaHoc","Home")

WebHocAnhVanNew/Views/KhoaHoc/CreateKH.cshtml
@model WebHocAnhVanNew.Models.KhoaHoc

@{
    ViewBag.Title = "CreateKH";
    Layout = "~/Views/Shared/Layoutql.cshtml";
}

<h2>CreateKH</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>KhoaHoc</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.TenKhoaHoc, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenKhoaHoc, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenKhoaHoc, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Mota, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Mota, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Mota, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Gia, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Gia, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Gia, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NgayXuatBan, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NgayXuatBan, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NgayXuatBan, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Hinh, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Hinh, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Hinh, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IdGV, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.IdGV, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.IdGV, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebHocAnhVanNew/Views/KhoaHoc/Delete.cshtml
@model WebHocAnhVanNew.Models.KhoaHoc

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/Layoutql.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>KhoaHoc</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenKhoaHoc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenKhoaHoc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mota)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mota)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayXuatBan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayXuatBan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdGV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdGV)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebHocAnhVanNew/Views/KhoaHoc/EditKH.cshtml
@model WebHocAnhVanNew.Models.KhoaHoc

@{
    ViewBag.Title = "EditKH";
    Layout = "~/Views/Shared/Layoutql.cshtml";
}

<h2>EditKH</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>KhoaHoc</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdKhoaHoc)

        <div class="form-group">
            @Html.LabelFor(model => model.TenKhoaHoc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenKhoaHoc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenKhoaHoc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mota, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mota, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mota, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayXuatBan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayXuatBan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayXuatBan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Hinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Hinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Hinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdGV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdGV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdGV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebHocAnhVanNew/Views/KhoaHoc/ListKH.cshtml
@model IEnumerable<WebHocAnhVanNew.Models.KhoaHoc>

@{
    ViewBag.Title = "ListKH";
    Layout = "~/Views/Shared/Layoutql.cshtml";
}

<h2>ListKH</h2>

<p>
    @Html.ActionLink("Create New", "CreateKH")
</p>
@using (Html.BeginForm("ListKH","KhoaHoc"))
{
    <div style="text-align:center">
        <b>Search By:</b> @Html.RadioButton("searchBy", "TenKhoaHoc")<text>AnhVan</text>
        @Html.RadioButton("searchBy", "GiangVien")<text>GiangVien</text>
        @Html.RadioButton("searchBy", "None")<text>None</text>
        @Html.TextBox("Search")<input type="submit" value="Search" />
    </div>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TenKhoaHoc)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Mota)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NgayXuatBan)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Hinh)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Giangvien.HoTenGV)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TenKhoaHoc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mota)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgayXuatBan)
            </td>
            <td>

                <img src="@item.Hinh " width="100px" height="100px" />

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Giangvien.HoTenGV)
            </td>
            <td>
                @Html.ActionLink("Edit", "EditKH", new { id = item.IdKhoaHoc }) |
                
                @Html.ActionLink("Delete", "Delete", new { id = item.IdKhoaHoc })
            </td>
        </tr>
    }

</table>